import { LAZORA_URL } from "./config";
import type { Project } from "./projects";

export const negocios: Project[] = [
  {
    slug: "dom-perfumes",
    status: "live",
    image: "/assets/img/projects/dom.png",
    imageFit: "cover",
    placeholderLabel: "DOM",
    type: "E-commerce & Perfumaria",
    name: "Dom Perfumes",
    desc: "Loja de perfumes árabes e de nicho. Cuidei da precificação, montei o dashboard de analytics interno e integrei o fornecedor via Shopify API.",
    stack: ["Angular", "Node.js", "PostgreSQL", "Shopify API"],
    link: { kind: "external", href: "https://domperfumes.com.br" },
  },
  {
    slug: "korza",
    status: "live",
    image: "/assets/img/projects/korza.png",
    imageFit: "contain",
    placeholderLabel: "KORZA",
    type: "SaaS",
    name: "Korza",
    desc: "SaaS que conecta lojas Shopify a um app mobile. Construí o dashboard do lojista e as APIs de backend. Sem desenvolvimento ativo hoje, mas o produto segue no ar.",
    stack: ["Angular", "Node.js", "TypeScript", "PostgreSQL"],
    link: { kind: "external", href: "https://korza-wine.vercel.app/" },
  },
  {
    slug: "lazy-promos",
    status: "live",
    image: "/assets/img/projects/lazypromos.png",
    imageFit: "cover",
    placeholderLabel: "LAZY",
    type: "Comunidade & Afiliados",
    name: "Lazy Promos",
    desc: "Comunidade de achadinhos no WhatsApp e Instagram. Cuido da curadoria, da automação por trás dela e da primeira comissão de afiliado que já saiu do papel, confirmada na Mercado Livre.",
    stack: ["Next.js", "Meta Pixel", "Mercado Livre API"],
    link: { kind: "external", href: "https://lazypromos.com.br" },
  },
  {
    slug: "silcore",
    status: "live",
    image: "/assets/img/projects/silcore.png",
    imageFit: "cover",
    placeholderLabel: "SILCORE",
    type: "Marca Própria & E-commerce D2C",
    name: "Silcore",
    desc: "Marca de arte em silicone, tapetes e placas com relevo 3D de times de futebol. Toquei cada etapa: produção, catálogo e venda, direto e pelo Mercado Livre.",
    stack: ["Next.js", "TypeScript", "Tailwind", "Framer Motion"],
    link: { kind: "external", href: "https://sili-art.vercel.app" },
  },
  {
    slug: "gigivariedades",
    status: "live",
    image: "/assets/img/projects/gigivariedades.png",
    imageFit: "cover",
    placeholderLabel: "GIGI",
    type: "Landing Page & Conversão (Atacado)",
    name: "GiGi Variedades",
    desc: "Landing page de conversão pra abertura de vertente de atacado de uma loja com quase dois anos de histórico e mais de 20 mil avaliações na Shopee. Entrei pra estruturar essa nova frente do zero.",
    stack: ["Next.js", "Three.js", "Framer Motion", "Vercel"],
    link: { kind: "external", href: "https://gi-gi-variedades.vercel.app/" },
  },
  {
    slug: "lazora",
    status: "live",
    image: null,
    imageFit: "cover",
    placeholderLabel: "LAZORA",
    type: "IA Generativa & Food Service",
    name: "Lazora",
    desc: "Geração de imagem de cardápio por IA pra quem vende comida e não tem verba de estúdio. Fundei e toco sozinho: prompt, pipeline de geração e atendimento. Primeiro cliente real rodando, a CQ Sabe Lanches.",
    stack: ["IA Generativa", "Next.js", "Cardápio Digital"],
    link: LAZORA_URL
      ? { kind: "external", href: LAZORA_URL }
      : { kind: "pending", label: "Site próprio em breve" },
  },
];
